version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=todos
    ports:
      - '5432:5432'

  api:
    image: skillfactoryteam/todos-api:1.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todos
    depends_on:
      - db
    ports:
      - '8080:8080'

  client:
    image: skillfactoryteam/vue-todos:1.0
    depends_on:
      - api
    ports:
      - '8081:8081'
